version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: school-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: school123
      MYSQL_DATABASE: school_management
      MYSQL_USER: school_user
      MYSQL_PASSWORD: school123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 